matrix:
  include:
    - language: rust
      rust:
        - stable
      os:
        - linux
        - osx
        - windows
      cache: cargo
      script:
        - cd rust
        - cargo test --verbose --all --release
    - language: scala
      os:
        - linux
      cache:
        directories:
          - $HOME/.ivy2/cache
          - $HOME/.sbt
      before_cache:
        - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
        - find $HOME/.sbt        -name "*.lock"               -delete
      script:
        - cd sbt
        - sbt test
